### ISSUE TITLE
Enabling this on Godot for new users

### ISSUE THREAD

**Issue by footballdaddy** [MarianoGnu/Godot-Tileset-Editor#1]
I am unable to enable the godot tileset editor. Even tried downloading the whole project and just to see if the settings were are already setup but it just shows regular tiled map options. I knows how install plugins though, as I have tiledmapimporter on but these addons are confusing. A Quick youtube vid showing would be awesome.

**Comment by MarianoGnu** [comment]
Hello bro.
First of all, this is not finished and wont be able to use these tiles yet.
Second, you need to build Godot from source to be able to use this addon.
Third, Once you builded from source and copied the addons folder to your project, you need to go to Project Settings and enable the plugin in the Plugins Tab

**Comment by MarianoGnu** [comment]
This one is outdated, i started to make this plugin with Godot2.1 unstable, so i'll close this issue. Not even sure if this repo works on Godot 2.1 stable
